version: "3"
services:
  react:
    build: ./front
    ports:
      - 3000:3000
      - 35729:35729
    links:
      - nodejs
    volumes:
      - ./front:/app
    environment:
      REACT_APP_BACK_HOST: localhost
      REACT_APP_BACK_PORT: 5000

  nodejs:
    build: ./back
    ports:
      - 5000:5000
    volumes:
      - ./back:/app
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
  
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    